export const START_GOOGLE_LOGIN = 'START_GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESSFUL = 'GOOGLE_LOGIN_SUCCESSFUL';
export const GOOGLE_LOGIN_FAILED = 'GOOGLE_LOGIN_FAILED';

export const START_KAKAO_LOGIN = 'START_KAKAO_LOGIN';
export const KAKAO_LOGIN_SUCCESSFUL = 'KAKAO_LOGIN_SUCCESSFUL';
export const KAKAO_LOGIN_FAILED = 'KAKAO_LOGIN_FAILED';
